[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "part1_bench"
harness = false

[[bench]]
name = "part2_bench"
harness = false

[dependencies]
